-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: check-symlinks
    - id: mixed-line-ending
    - id: pretty-format-json
      args: [--autofix, --indent=4]
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: no-commit-to-branch

- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.1.0
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
